# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Prometheus SSH exporter paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ prometheus_ssh_exporter_uid }}"
    group: "{{ prometheus_ssh_exporter_gid }}"
  with_items:
    - "{{ prometheus_ssh_exporter_base_path }}"
    - "{{ prometheus_ssh_exporter_config_path }}"

- name: Ensure Prometheus SSH exporter labels file installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ prometheus_ssh_exporter_config_path }}/labels"
    owner: "{{ prometheus_ssh_exporter_uid }}"
    group: "{{ prometheus_ssh_exporter_gid }}"
    mode: "0640"

- name: Ensure Prometheus SSH exporter configuration file installed
  ansible.builtin.copy:
    content: "{{ prometheus_ssh_exporter_configuration | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ prometheus_ssh_exporter_config_path }}/config.yaml"
    owner: "{{ prometheus_ssh_exporter_uid }}"
    group: "{{ prometheus_ssh_exporter_gid }}"
    mode: "0640"

- name: Ensure Prometheus SSH exporter image is pulled
  community.docker.docker_image:
    name: "{{ prometheus_ssh_exporter_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ prometheus_ssh_exporter_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else prometheus_ssh_exporter_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Prometheus SSH exporter container network is created
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ prometheus_ssh_exporter_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  when: prometheus_ssh_exporter_container_network != 'host'

- name: Ensure Prometheus SSH exporter systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/prometheus-ssh-exporter.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ prometheus_ssh_exporter_identifier }}.service"
    mode: "0644"
