# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Prometheus SSH exporter installation tasks
  when: prometheus_ssh_exporter_enabled | bool
  tags:
    - setup-all
    - setup-prometheus-ssh-exporter
    - install-all
    - install-prometheus-ssh-exporter
  block:
    - name: Validate Prometheus SSH exporter configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Prometheus SSH exporter
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Prometheus SSH exporter uninstallation tasks
  when: not prometheus_ssh_exporter_enabled | bool
  tags:
    - setup-all
    - setup-prometheus-ssh-exporter
  block:
    - name: Uninstall Prometheus SSH exporter
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
