# SPDX-FileCopyrightText: 2023 Nikita Chernyi
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Prometheus SSH exporter service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ prometheus_ssh_exporter_identifier }}.service"
  register: prometheus_ssh_exporter_service_stat

- name: Uninstall Prometheus SSH exporter systemd services and files
  when: prometheus_ssh_exporter_service_stat.stat.exists | bool
  block:
    - name: Ensure Prometheus SSH exporter systemd service is stopped
      ansible.builtin.service:
        name: "{{ prometheus_ssh_exporter_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Prometheus SSH exporter service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ prometheus_ssh_exporter_identifier }}.service"
        state: absent

    - name: Ensure Prometheus SSH exporter container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ prometheus_ssh_exporter_container_network }}"
        state: absent

    - name: Ensure Prometheus SSH exporter container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ prometheus_ssh_exporter_container_network }}
      register: network_deletion_result
      changed_when: prometheus_ssh_exporter_container_network in network_deletion_result.stdout

    - name: Ensure Prometheus SSH exporter path does not exist
      ansible.builtin.file:
        path: "{{ prometheus_ssh_exporter_base_path }}"
        state: absent
