---
- name: Fail if required prometheus-ssh-exporter settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - prometheus_ssh_exporter_uid
    - prometheus_ssh_exporter_gid
    - prometheus_ssh_exporter_container_network

- when: prometheus_ssh_exporter_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required prometheus-ssh-exporter Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - prometheus_ssh_exporter_container_labels_traefik_hostname

